title: Pace in Palestina
description: Pagina di supporto per le azioni a favore della pace in Palestina del gruppo Un Grido per Gaza a Pisa.
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
